version: 2

sources:
  - name: m5_raw
    database: vocal-seeker-508915-g3
    schema: retail_demand_raw

    tables:
      - name: calendar
      - name: sales_train_validation
      - name: sell_prices